#!/usr/bin/env bash

if [ -e "node_modules/root" ]
then
  rm -f node_modules/root
fi
ln -sf ../ node_modules/root

if [ -e "node_modules/modules" ]
then
  rm -f node_modules/modules
fi
ln -sf ../modules node_modules/modules
